### ISSUE TITLE
scrollTo blocks scrolling on Safari

### ISSUE THREAD

**Issue by VladDigitalOriginal** [darkroomengineering/lenis#218] opened 2023-08-18 14:16 UTC
I'm using scrollTo with duration: 8, for some smooth animation, based on scroll. I've tried to configure it `lenis.scrollTo(initialPosition, { duration: 8, lock: false, force: false })`, but it still blocks scrolling on Safari

**Comment by clementroche** [comment] 2023-08-21 07:46
please provide a codesandbox

**Comment by VladDigitalOriginal** [comment] 2023-08-21 10:42
### The bug is only reproduced in preview in Safari.
### Maybe some refreshes required to reproduce.

`npm run build`
`npm run preview`

[codesandbox](https://codesandbox.io/p/sandbox/shoty-387v87)

_edit: update codesandbox link_

**Comment by clementroche** [comment] 2023-08-29 09:39
Which version of Safari are you using ? It works for me using 16.4.

**Comment by VladDigitalOriginal** [comment] 2023-08-29 10:31
My Safari version is 16.6, but I've also encountered it in previous versions. You can try to check it [here](https://387v87-3000.csb.app); a few reloads may be required. Additionally, there is a `rotateY` based on `velocity`, and when this bug occurs, the `velocity` is always equal to 0.

Here is a video where I attempt to scroll, but it appears to be "locked":

[[Video Link](](https://github.com/studio-freight/lenis/assets/122997283/3df9c790-41db-4df6-beab-73159597b1bc)

**Comment by clementroche** [comment] 2023-08-29 11:43
@VladDigitalOriginal are you trying to scroll during the scrollTo animation ?

**Comment by VladDigitalOriginal** [comment] 2023-08-29 13:35
@clementroche yes

**Comment by clementroche** [comment] 2023-08-30 16:11
maybe related https://github.com/studio-freight/lenis/issues/103

**Comment by VladDigitalOriginal** [comment] 2023-08-30 16:34
I had the same issue as [#103](https://github.com/studio-freight/lenis/issues/103) and `wrapper: document.body` fixed it, but problem with locked scrollTo (and zero velocity) remains

**Comment by clementroche** [comment] 2024-02-08 21:23
i can't reproduce, i'm closing this.

**Closed as completed by clementroche** 2024-02-08 21:23 UTC
