### ISSUE TITLE
NaN if Lenis is created while wheel events are coming in

### ISSUE THREAD

**Issue by ffdead** [darkroomengineering/lenis#21] opened 2022-09-12 11:12 UTC
Hi guys, thanks for a great lib!

I noticed that reloading the page while wheel events (trackpad on a Macbook pro) are still coming in, the onscroll returns `NaN` as value and then scrolling breaks. 

You can recreate by scrolling to top on the demo site and quickly reloading at the top:

<img width="1451" alt="Screenshot 2022-09-12 at 13 12 06" src="https://user-images.githubusercontent.com/420472/189639498-6f76b53f-e9b7-40a9-a2b4-a95a475c88db.png">

**Comment by arzafran** [comment] 2022-09-12 11:28
Hello! thanks for flagging this, i'm reviewing if the issue is on the library or the website, will keep you posted! 
– btw the site is a WIP, we're going to announce it when it's ready, what are your thoughts on it so far?

**Comment by ffdead** [comment] 2022-09-12 11:39
> i'm reviewing if the issue is on the library or the website

I got the same issue in my codebase so it must be in the library. maybe something related to the wheel events coming in too early? As mentioned on Twitter a while back I'm looking into integrating this to our 14islands scroll-rig, getting very promising results so far! 

Unrelated question, any perticular reason why you went for a fixed time easing intead of @14islands/lerp? I'm happy using expoOut so no problem there 👌 

Love the example site, great job guys!

**Comment by arzafran** [comment] 2022-09-12 13:03
Thanks! we're still defining stuff and we wanted to keep moving parts to a minimum, feel free to open a PR with your lerp added we would love to see it working!

**Comment by clementroche** [comment] 2022-09-12 15:18
Thanks, the issue is fixed with v0.2.2

**Closed as completed by clementroche** 2022-09-12 15:18 UTC
