### ISSUE TITLE
Scroll top problem only on IOS

### ISSUE THREAD

**Issue by atoupet-toki** [darkroomengineering/lenis#288] opened 2024-01-31 19:59 UTC
Hello!
We have a scroll top problem only on IOS (safari/chrome).
When the page loads, we scroll a little and HOP the site scrolls up completely, and then everything works correctly again.
Our new/future database contains GSAP/SWUP/Lenis.

Here's some of the code used to init lenis, and the associated scss:

```
window.lenis = new Lenis({
    smoothWheel: true,
    smoothTouch: false,
    duration: 1.1,
    easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
});
window.lenis.on('scroll', () => {
    ScrollTrigger.update;
});
gsap.ticker.add((time) => {
    window.lenis.raf(time * 1000);
});
```
```
html.lenis {
    height: auto;

    &.lenis-smooth {
        scroll-behavior: auto;
    }
    &.lenis-smooth [data-lenis-prevent] {
        overscroll-behavior: contain;
    }
    &.lenis-stopped {
        overflow: hidden;
    }
    &.lenis-scrolling iframe {
        pointer-events: none;
    }
}
```

Have you ever had a similar problem?

**Comment by clementroche** [comment] 2024-01-31 20:12
smoothTouch has been removed from Lenis, please use syncTouch instead

**Comment by atoupet-toki** [comment] 2024-02-01 16:57
Thanks for your quick feedback!
It doesn't seem to work ... but I managed with the following js: `ScrollTrigger.config({ ignoreMobileResize: true });`

**Comment by clementroche** [comment] 2024-02-02 17:06
What version of lenis do you use ?

**Comment by atoupet-toki** [comment] 2024-02-02 19:29
1.0.34

**Comment by clementroche** [comment] 2024-02-03 11:26
Would you mind sharing a codepen/codesandbox ?

**Comment by cyocun** [comment] 2024-02-08 02:43
I'm also having the same problem.

If you scroll the window a little and speak, you will be scrolled back to the beginning of the page.
If you scroll a lot (maybe a screen or two), you'll be able to scroll normally from then on.

And I am also using ScrollTrigger within the page. I am unable to provide sample code immediately.
`ScrollTrigger.config({ ignoreMobileResize: true });`
I would like to try this.

**Comment by clementroche** [comment] 2024-03-09 16:21
I'm closing this issue until you provide a minimal reproduction link.

**Closed as completed by clementroche** 2024-03-09 16:21 UTC

**Comment by Slgoetz** [comment] 2024-06-04 17:05
I am seeing the same issue on `"lenis": "^1.1.1"`

**Comment by immiProgrammer** [comment] 2024-06-05 08:43
i fase this problem

**Comment by clementroche** [comment] 2024-06-05 10:24
Your issue might be caused by Scrolltriger itself, not Lenis, try to remove ScrollTrigger and see if it still happens. If so take a look at this https://gsap.com/docs/v3/Plugins/ScrollTrigger/static.clearScrollMemory()/
