### ISSUE TITLE
deltaX is not defined on touchMove

### ISSUE THREAD

**Issue by leo-cheron** [darkroomengineering/lenis#163] opened 2023-04-20 10:24 UTC
**Describe the bug**
[This commit](https://github.com/studio-freight/lenis/commit/1c7cbab1db94fc97a85515015bcf770863a4eadc) breaks VirtualScroller touchMove event handler, as deltaX and deltaY are not properly declared.

**To Reproduce**
Simulate a mobile view, dragging anywhere will trigger a `deltaX is not defined` error.

**Additional comments**
This error also occurs when `smoothTouch` is set to false. Touch events probably not be listened in that case. 

**version**
1.0.9

**Comment by clementroche** [comment] 2023-04-20 11:27
Can you provide a codepen or something because i cannot reproduce on my side @mrgnou

**Comment by clementroche** [comment] 2023-04-20 20:22
Sorry: fixed in v1.0.10

**Closed as completed by clementroche** 2023-04-20 20:22 UTC
